replicaCount: 2

image:
  repository: ghcr.io/fwartner/photo-booth
  tag: latest
  pullPolicy: Always

host: photo-booth.preview.remon-infra.de

tls:
  secretName: wildcard-preview-remon-infra-tls

service:
  port: 80
  targetPort: 3000
